name: Node.js CI - User Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: exploresl
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1212
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Sequelize Sync (simple test)
      env:
        DB_NAME: exploresl
        DB_USER: postgres
        DB_PASS: 1212
        DB_HOST: localhost
      run: node index.js
