name: Node.js CI - User Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: exploresl
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Change to user-service folder
      run: cd user-service

    - name: Install dependencies
      run: |
        cd user-service
        npm install

    - name: Run Sequelize Sync
      env:
        DB_NAME: exploresl
        DB_USER: postgres
        DB_PASS: postgres
        DB_HOST: localhost
      run: |
        cd user-service
        node index.js